title: Marcos Personal Homepage
author: Marcos F.
description: Personal webpage with stuff built by me or things I consider interesting, around physics and computing.
# _config.yml
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
  math_engine: mathjax
  parse_block_html: true

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

# Exclude files that interfere
exclude:
  - Gemfile
  - Gemfile.lock
  
theme: minima
baseurl: "/marcosst"
url: "https://marc029github.github.io"
minima:
  skin: classic
  social_links:
    github: marc029github
show_excerpts: true
header_pages:
  - physics/index.md
  - computing/index.md
  - other/index.md
  - about.md
collections:
  physics:
    output: true
    permalink: /physics/:title
  computing:
    output: true
    permalink: /computing/:title
  other:
    output: true
    permalink: /other/:title
