title: My Homepage
author: Marcos F.
description: Personal webpage with Physics and Computing blogs, bio, and GitHub links
theme: minima
baseurl: "/marcosst"
url: "https://marc029github.github.io"
minima:
  skin: classic
  social_links:
    github: marc029github
show_excerpts: true
header_pages:
  - physics/index.md
  - computing/index.md
  - other/index.md
  - about.md
collections:
  physics:
    output: true
    permalink: /physics/:title
  computing:
    output: true
    permalink: /computing/:title
  other:
    output: true
    permalink: /other/:title