title: Marcos F.
   author: Marcos F.
   description: Personal webpage with Physics and Computing blogs, bio, and GitHub links
   theme: minima
   baseurl: ""
   url: "https://marc029github.github.io/marcosst/"
   minima:
     skin: classic
     social_links:
       github: marc029github
   show_excerpts: true
   header_pages:
     - physics/index.md
     - computing/index.md
     - about.md
   collections:
     physics:
       output: true
       permalink: /physics/:title
     computing:
       output: true
       permalink: /computing/:title